### PR TITLE
Vcpkg as a submodule

### PR DESCRIPTION
**Pull request by BeauSLM**
initialize the project quickly and easily:
- no installing vcpkg yourself
- no setting variables in scripts (git worktree remains clean yaaayyyy)
- run 1 script to install vcpkg, dependencies ~, and then to build project~, build with visual studio + cmake

### CODE REVIEW

**Comment by BeauSLM** [comment]
NOTE: untested on windows, I will do soon and update if necessary. Please DO NOT MERGE until we know it works on windows

**Review by dylanleclair — APPROVED** [review]
approved pending working on windows !!

**Comment by BeauSLM** [comment]
I should that this approach isn't perfect. `vcpkg` installs stuff in directories outside the project, but it's a local dependency in the project.

One solution could be to set up a script that installs vcpkg in a standardized short path (like they recommend https://vcpkg.io/en/getting-started.html) and a `.gitignore`-d .envrc file (for direnv) that sets the env var CMAKE_TOOLCHAIN_FILE to that standardized directory. This approach preserves my approaches's clean git tree (no tracked file is edited with a hard-coded local filepath), and like dylan's original approach it allows for a global install of `vcpkg` so you can use `vcpkg` in other projects (including the dependencies that it caches, download sdl2 only once for all your projects).

Moral of the story: package managers suck but we love them.

**Comment by BeauSLM** [comment]
works on mine and Elise's machine's, merged

**Pull request merged**
